// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/chouca.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// local_dens
arma::Col<arma::uword> local_dens(const arma::Mat<unsigned short> m, const arma::uword nstates, const arma::uword i, const arma::uword j, const bool wrap, const bool use_8_nb);
RcppExport SEXP _chouca_local_dens(SEXP mSEXP, SEXP nstatesSEXP, SEXP iSEXP, SEXP jSEXP, SEXP wrapSEXP, SEXP use_8_nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<unsigned short> >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type i(iSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type j(jSEXP);
    Rcpp::traits::input_parameter< const bool >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_8_nb(use_8_nbSEXP);
    rcpp_result_gen = Rcpp::wrap(local_dens(m, nstates, i, j, wrap, use_8_nb));
    return rcpp_result_gen;
END_RCPP
}
// local_dens_col
arma::Mat<arma::uword> local_dens_col(const arma::Mat<unsigned short> m, const arma::uword nstates, const arma::uword j, const bool wrap, const bool use_8_nb);
RcppExport SEXP _chouca_local_dens_col(SEXP mSEXP, SEXP nstatesSEXP, SEXP jSEXP, SEXP wrapSEXP, SEXP use_8_nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<unsigned short> >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type j(jSEXP);
    Rcpp::traits::input_parameter< const bool >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_8_nb(use_8_nbSEXP);
    rcpp_result_gen = Rcpp::wrap(local_dens_col(m, nstates, j, wrap, use_8_nb));
    return rcpp_result_gen;
END_RCPP
}
// camodel_cpp_engine
void camodel_cpp_engine(const Rcpp::List ctrl);
RcppExport SEXP _chouca_camodel_cpp_engine(SEXP ctrlSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type ctrl(ctrlSEXP);
    camodel_cpp_engine(ctrl);
    return R_NilValue;
END_RCPP
}
// generate_all_qs
arma::umat generate_all_qs(arma::uword nb, arma::uword ns, arma::uword filter, arma::uword line_cap);
RcppExport SEXP _chouca_generate_all_qs(SEXP nbSEXP, SEXP nsSEXP, SEXP filterSEXP, SEXP line_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type line_cap(line_capSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_all_qs(nb, ns, filter, line_cap));
    return rcpp_result_gen;
END_RCPP
}
// quick_pred_cpp
arma::vec quick_pred_cpp(const arma::vec coefs, const arma::mat ps, const arma::mat qs, const arma::mat vals);
RcppExport SEXP _chouca_quick_pred_cpp(SEXP coefsSEXP, SEXP psSEXP, SEXP qsSEXP, SEXP valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type ps(psSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type qs(qsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type vals(valsSEXP);
    rcpp_result_gen = Rcpp::wrap(quick_pred_cpp(coefs, ps, qs, vals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chouca_local_dens", (DL_FUNC) &_chouca_local_dens, 6},
    {"_chouca_local_dens_col", (DL_FUNC) &_chouca_local_dens_col, 5},
    {"_chouca_camodel_cpp_engine", (DL_FUNC) &_chouca_camodel_cpp_engine, 1},
    {"_chouca_generate_all_qs", (DL_FUNC) &_chouca_generate_all_qs, 4},
    {"_chouca_quick_pred_cpp", (DL_FUNC) &_chouca_quick_pred_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_chouca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
