// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/chouca.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// camodel_cpp_engine
void camodel_cpp_engine(const Rcpp::List ctrl);
RcppExport SEXP _chouca_camodel_cpp_engine(SEXP ctrlSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type ctrl(ctrlSEXP);
    camodel_cpp_engine(ctrl);
    return R_NilValue;
END_RCPP
}
// local_dens_col
arma::Mat<arma::uword> local_dens_col(const arma::Mat<unsigned short>& m, const arma::uword& nstates, const arma::uword& j, const bool& wrap, const arma::Mat<unsigned short>& kernel);
RcppExport SEXP _chouca_local_dens_col(SEXP mSEXP, SEXP nstatesSEXP, SEXP jSEXP, SEXP wrapSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<unsigned short>& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type j(jSEXP);
    Rcpp::traits::input_parameter< const bool& >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< const arma::Mat<unsigned short>& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(local_dens_col(m, nstates, j, wrap, kernel));
    return rcpp_result_gen;
END_RCPP
}
// get_transition_probas_cpp
arma::cube get_transition_probas_cpp(arma::Mat<ushort>& mat, Rcpp::List& ctrl);
RcppExport SEXP _chouca_get_transition_probas_cpp(SEXP matSEXP, SEXP ctrlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<ushort>& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ctrl(ctrlSEXP);
    rcpp_result_gen = Rcpp::wrap(get_transition_probas_cpp(mat, ctrl));
    return rcpp_result_gen;
END_RCPP
}
// transition_ll
arma::mat transition_ll(const arma::Mat<ushort>& from_mat, const arma::Mat<ushort>& to_mat, const arma::cube& tprobs);
RcppExport SEXP _chouca_transition_ll(SEXP from_matSEXP, SEXP to_matSEXP, SEXP tprobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<ushort>& >::type from_mat(from_matSEXP);
    Rcpp::traits::input_parameter< const arma::Mat<ushort>& >::type to_mat(to_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type tprobs(tprobsSEXP);
    rcpp_result_gen = Rcpp::wrap(transition_ll(from_mat, to_mat, tprobs));
    return rcpp_result_gen;
END_RCPP
}
// generate_all_qs
arma::umat generate_all_qs(arma::uword nb, arma::uword ns, arma::uword filter, arma::uword line_cap);
RcppExport SEXP _chouca_generate_all_qs(SEXP nbSEXP, SEXP nsSEXP, SEXP filterSEXP, SEXP line_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type line_cap(line_capSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_all_qs(nb, ns, filter, line_cap));
    return rcpp_result_gen;
END_RCPP
}
// quick_pred_cpp
arma::vec quick_pred_cpp(const arma::vec coefs, const arma::mat ps, const arma::mat qs, const arma::mat vals);
RcppExport SEXP _chouca_quick_pred_cpp(SEXP coefsSEXP, SEXP psSEXP, SEXP qsSEXP, SEXP valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type ps(psSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type qs(qsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type vals(valsSEXP);
    rcpp_result_gen = Rcpp::wrap(quick_pred_cpp(coefs, ps, qs, vals));
    return rcpp_result_gen;
END_RCPP
}
// get_cell_qvec
arma::vec get_cell_qvec(const arma::Mat<unsigned short>& m, const arma::uword& i_R, const arma::uword& j_R, const arma::uword ns, const bool& wrap, const arma::Mat<unsigned short>& kernel);
RcppExport SEXP _chouca_get_cell_qvec(SEXP mSEXP, SEXP i_RSEXP, SEXP j_RSEXP, SEXP nsSEXP, SEXP wrapSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<unsigned short>& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type i_R(i_RSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type j_R(j_RSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< const arma::Mat<unsigned short>& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(get_cell_qvec(m, i_R, j_R, ns, wrap, kernel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chouca_camodel_cpp_engine", (DL_FUNC) &_chouca_camodel_cpp_engine, 1},
    {"_chouca_local_dens_col", (DL_FUNC) &_chouca_local_dens_col, 5},
    {"_chouca_get_transition_probas_cpp", (DL_FUNC) &_chouca_get_transition_probas_cpp, 2},
    {"_chouca_transition_ll", (DL_FUNC) &_chouca_transition_ll, 3},
    {"_chouca_generate_all_qs", (DL_FUNC) &_chouca_generate_all_qs, 4},
    {"_chouca_quick_pred_cpp", (DL_FUNC) &_chouca_quick_pred_cpp, 4},
    {"_chouca_get_cell_qvec", (DL_FUNC) &_chouca_get_cell_qvec, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_chouca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
