# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getline <- function(qs, nb, ns) {
    .Call(`_chouca_getline`, qs, nb, ns)
}

simple_sum <- function(qs, nb, ns) {
    .Call(`_chouca_simple_sum`, qs, nb, ns)
}

local_dens <- function(m, nstates, i, j, wrap, use_8_nb) {
    .Call(`_chouca_local_dens`, m, nstates, i, j, wrap, use_8_nb)
}

local_dens_col <- function(m, nstates, j, wrap, use_8_nb) {
    .Call(`_chouca_local_dens_col`, m, nstates, j, wrap, use_8_nb)
}

camodel_cpp_engine <- function(alpha_index, alpha_vals, pmat_index, pmat_vals, qmat_index, qmat_vals, ctrl, console_callback, cover_callback, snapshot_callback) {
    invisible(.Call(`_chouca_camodel_cpp_engine`, alpha_index, alpha_vals, pmat_index, pmat_vals, qmat_index, qmat_vals, ctrl, console_callback, cover_callback, snapshot_callback))
}

aaaa0d91609dd70176756315aa3d03e6a5bcamodel_compiled_engine <- function(alpha_index, alpha_vals, pmat_index, pmat_vals, qmat_index, qmat_vals, ctrl, console_callback, cover_callback, snapshot_callback) {
    invisible(.Call(`_chouca_aaaa0d91609dd70176756315aa3d03e6a5bcamodel_compiled_engine`, alpha_index, alpha_vals, pmat_index, pmat_vals, qmat_index, qmat_vals, ctrl, console_callback, cover_callback, snapshot_callback))
}

