# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

camodel_cpp_engine <- function(ctrl) {
    invisible(.Call(`_chouca_camodel_cpp_engine`, ctrl))
}

local_dens_col <- function(m, nstates, j, wrap, kernel) {
    .Call(`_chouca_local_dens_col`, m, nstates, j, wrap, kernel)
}

get_transition_probas_cpp <- function(mat, ctrl, return_log = FALSE) {
    .Call(`_chouca_get_transition_probas_cpp`, mat, ctrl, return_log)
}

transition_ll <- function(from_mat, to_mat, tprobs) {
    .Call(`_chouca_transition_ll`, from_mat, to_mat, tprobs)
}

generate_all_qs <- function(nb, ns, filter, line_cap) {
    .Call(`_chouca_generate_all_qs`, nb, ns, filter, line_cap)
}

quick_pred_cpp <- function(coefs, ps, qs, vals) {
    .Call(`_chouca_quick_pred_cpp`, coefs, ps, qs, vals)
}

get_cell_qvec <- function(m, i_R, j_R, ns, wrap, kernel) {
    .Call(`_chouca_get_cell_qvec`, m, i_R, j_R, ns, wrap, kernel)
}

