# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

local_dens <- function(m, nstates, i, j, wrap, use_8_nb) {
    .Call(`_chouca_local_dens`, m, nstates, i, j, wrap, use_8_nb)
}

local_dens_col <- function(m, nstates, j, wrap, use_8_nb) {
    .Call(`_chouca_local_dens_col`, m, nstates, j, wrap, use_8_nb)
}

camodel_cpp_engine <- function(trans, ctrl, console_callback, cover_callback, snapshot_callback) {
    invisible(.Call(`_chouca_camodel_cpp_engine`, trans, ctrl, console_callback, cover_callback, snapshot_callback))
}

getline <- function(qs, nb, ns) {
    .Call(`_chouca_getline`, qs, nb, ns)
}

simple_sum <- function(qs, nb, ns) {
    .Call(`_chouca_simple_sum`, qs, nb, ns)
}

